openapi: '3.0.3'
info:
  title: API Title
  description: Detailed description of what the API does.
  version: '1.0'
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.server.test/v1
tags:
  - name: Testing
    description: API endpoints related to testing functionalities.
paths:
  /test:
    get:
      tags:
        - Testing
      summary: Retrieve test information
      description: This endpoint retrieves test-related data.
      operationId: getTestInfo
      parameters:
        - name: id
          in: query
          required: false
          description: The ID of the test item.
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
              examples:
                example1:
                  value:
                    id: "123"
                    name: "Test Name"
        '400':
          description: Bad Request
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    TestItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
security:
  - ApiKeyAuth: []

